// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfSc_cJ64rVlXlooS1cXnkkmsa_gjOYRs',
    appId: '1:1082649727590:web:227e5502f10721fdc313a7',
    messagingSenderId: '1082649727590',
    projectId: 'algeon-66295',
    authDomain: 'algeon-66295.firebaseapp.com',
    storageBucket: 'algeon-66295.firebasestorage.app',
    measurementId: 'G-1TRCQ364ZW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOhbqFS5B7t_oxmGQ9ge1ldLQtfPUK_rA',
    appId: '1:1082649727590:ios:1762e0625c40d5d0c313a7',
    messagingSenderId: '1082649727590',
    projectId: 'algeon-66295',
    storageBucket: 'algeon-66295.firebasestorage.app',
    iosClientId: '1082649727590-ir08b3vg7qbs2b4epsluivc8vlaqu5cv.apps.googleusercontent.com',
    iosBundleId: 'com.algeon.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx3GGskctLX9XmnIvgszTQ2203GZcT1B8',
    appId: '1:1082649727590:android:0a499cf595c9ff83c313a7',
    messagingSenderId: '1082649727590',
    projectId: 'algeon-66295',
    storageBucket: 'algeon-66295.firebasestorage.app',
  );

}